# Generated by Django 5.2.5 on 2025-08-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField()),
                ('recipe_description', models.TextField()),
                ('recipe_price', models.IntegerField(default=0)),
                ('recipe_image', models.ImageField(upload_to='recipe')),
            ],
        ),
    ]
